apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    name: opflexserver
    network-plugin: aci-containers
  name: opflexserver
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: opflexserver
      network-plugin: aci-containers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        name: opflexserver
        network-plugin: aci-containers
      name: opflexserver
      namespace: kube-system
    spec:
      containers:
      - image: challa/opflexserver:latest
        imagePullPolicy: Always
        name: opflexserver
        ports:
          - containerPort: 8009
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/etc/opflex-server
          name: opflex-server-config-volume
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: opflexserver
      serviceAccountName: opflexserver
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - name: opflex-server-config-volume
      nodeSelector:
        node-role.kubernetes.io/master: ""
